import re

with open('driftbound_flight_test.html', 'rb') as f:
    d = f.read().decode('utf-8', 'replace')

fixes = []

# ── helper: regex replace without re.sub interpolation issues ──
def rsub(pattern, replacement, text, flags=re.DOTALL):
    m = re.search(pattern, text, flags)
    if not m:
        return text, False
    return text[:m.start()] + replacement + text[m.end():], True

# ══════════════════════════════════════════════════════════════════
# 1. drawAttachedPods — physical pod tethered behind ship
# ══════════════════════════════════════════════════════════════════
NEW_AP = (
    'function drawAttachedPods(cx, cy) {\n'
    '  if (attachedPods.length) {\n'
    '    const t = Date.now() * 0.001;\n'
    '    const DIR_OFFSETS = {\n'
    '      north:{ox:0,oy:38},northeast:{ox:-27,oy:27},east:{ox:-38,oy:0},\n'
    '      southeast:{ox:-27,oy:-27},south:{ox:0,oy:-38},southwest:{ox:27,oy:-27},\n'
    '      west:{ox:38,oy:0},northwest:{ox:27,oy:27},\n'
    '    };\n'
    '    const off = DIR_OFFSETS[ship.dir] || {ox:0,oy:38};\n'
    '    attachedPods.forEach((pod, idx) => {\n'
    '      const dist  = 42 + idx * 36;\n'
    '      const ratio = dist / 38;\n'
    '      const px = cx + off.ox * ratio;\n'
    '      const py = cy + off.oy * ratio;\n'
    '      ctx.save();\n'
    '      ctx.strokeStyle = "#38bdf866"; ctx.lineWidth = 1.5;\n'
    '      ctx.setLineDash([4,4]);\n'
    '      ctx.beginPath(); ctx.moveTo(cx,cy); ctx.lineTo(px,py); ctx.stroke();\n'
    '      ctx.setLineDash([]);\n'
    '      ctx.translate(px, py + Math.sin(t*1.8+idx*1.2)*2);\n'
    '      ctx.shadowColor = pod.color || "#38bdf8"; ctx.shadowBlur = 10;\n'
    '      const podFrame = podRotations["south"];\n'
    '      if (podFrame) {\n'
    '        ctx.imageSmoothingEnabled = false;\n'
    '        ctx.drawImage(podFrame, -22, -22, 44, 44);\n'
    '      } else {\n'
    '        ctx.fillStyle = (pod.color||"#38bdf8")+"cc";\n'
    '        ctx.beginPath();\n'
    '        for(let k=0;k<6;k++){const a=(k/6)*Math.PI*2-Math.PI/6;\n'
    '          k===0?ctx.moveTo(Math.cos(a)*14,Math.sin(a)*14):ctx.lineTo(Math.cos(a)*14,Math.sin(a)*14);}\n'
    '        ctx.closePath(); ctx.fill();\n'
    '      }\n'
    '      ctx.shadowBlur=0; ctx.restore();\n'
    '    });\n'
    '  }\n'
    '  if (_autoSaveTimer > 1780) {\n'
    '    ctx.save(); ctx.textAlign="right"; ctx.font="11px Courier New";\n'
    '    ctx.fillStyle="#22c55e"; ctx.fillText("SAVING...", canvas.width-14, 16);\n'
    '    ctx.restore();\n'
    '  }\n'
    '}'
)

d, ok = rsub(r'function drawAttachedPods\(cx, cy\) \{.*?\n\}', NEW_AP, d)
fixes.append(('OK' if ok else 'FAIL') + ' drawAttachedPods physical pod')

# ══════════════════════════════════════════════════════════════════
# 2. Full HUD redesign
# ══════════════════════════════════════════════════════════════════
SEP   = '\u2014'   # em dash for display
ARR   = '\u2192'   # arrow
CROSS = '\u2715'   # x
WARN  = '\u26a0'   # warning
DIAM  = '\u25c6'   # diamond
LOZZ  = '\u2666'   # lozenge
OCTO  = '\u25c8'   # octagon
SQUA  = '\u25a0'   # square
TARG  = '\u29BF'   # target circle

NEW_HUD = (
    'function drawHUD(speed) {\n'
    '  const L=18, PW=310, LINE=22;\n'
    '  const SML="13px Courier New", MED="15px Courier New";\n'
    '  const DIM="#4a6070", TEAL="#4FC3C3", ORANGE="#D9541E", WHT="#c8d8e8";\n'
    '\n'
    '  function sBar(y, lbl, col) {\n'
    '    col = col||TEAL;\n'
    '    ctx.fillStyle=col+"28"; ctx.fillRect(10,y-14,PW,18);\n'
    '    ctx.fillStyle=col;      ctx.fillRect(10,y-14,3,18);\n'
    '    ctx.font="bold 11px Courier New"; ctx.fillStyle=col;\n'
    '    ctx.fillText(lbl, L+6, y);\n'
    '  }\n'
    '  function kv(key,val,x,y,vc) {\n'
    '    ctx.font=SML; ctx.fillStyle=DIM; ctx.fillText(key,x,y);\n'
    '    ctx.font=MED; ctx.fillStyle=vc||WHT; ctx.fillText(val,x+68,y);\n'
    '  }\n'
    '  function hbar(x,y,w,h,pct,c1,c2) {\n'
    '    ctx.fillStyle="#0d1520"; ctx.fillRect(x-1,y-1,w+2,h+2);\n'
    '    const g=ctx.createLinearGradient(x,0,x+w,0);\n'
    '    g.addColorStop(0,c1); g.addColorStop(1,c2||c1);\n'
    '    ctx.fillStyle=g; ctx.fillRect(x,y,w*Math.min(pct,1),h);\n'
    '    ctx.strokeStyle="#ffffff14"; ctx.lineWidth=1; ctx.strokeRect(x,y,w,h);\n'
    '  }\n'
    '\n'
    '  const resCount=(ship.ore>0?1:0)+(ship.mineral>0?1:0)+(ship.armalcolite>0?1:0);\n'
    '  const modRows =attachedPods.length;\n'
    '  const netRow  =(typeof multiMode!=="undefined"&&multiMode)?1:0;\n'
    '  const panelH  =312+resCount*LINE+(modRows?(LINE*(modRows+1)):0)+(netRow?LINE*2:0);\n'
    '\n'
    '  ctx.fillStyle="#000000e0"; ctx.fillRect(10,10,PW,panelH);\n'
    '  ctx.strokeStyle=TEAL+"30"; ctx.lineWidth=1; ctx.strokeRect(10,10,PW,panelH);\n'
    '  ctx.fillStyle=TEAL+"50";   ctx.fillRect(10,10,3,panelH);\n'
    '\n'
    '  let y=30;\n'
    '\n'
    '  // NAVIGATION\n'
    '  sBar(y,"NAVIGATION",TEAL); y+=LINE+2;\n'
    '  kv("SPD",speed.toFixed(2),L,y); y+=LINE;\n'
    '  kv("DIR",ship.dir.replace("-"," ").toUpperCase(),L,y); y+=LINE;\n'
    '  kv("POS",Math.floor(ship.worldX)+" / "+Math.floor(ship.worldY),L,y); y+=LINE+4;\n'
    '\n'
    '  // SHIP\n'
    '  sBar(y,"SHIP  "+ship.shipType.name,TEAL); y+=LINE+2;\n'
    '  ctx.font=SML; ctx.fillStyle=DIM; ctx.fillText("THRUST",L,y); y+=4;\n'
    '  hbar(L,y,PW-28,7,speed/BOOST_MAX,"#4FC3C3","#ff2222"); y+=16;\n'
    '  const hpPct=ship.hp/SHIP_MAX_HP;\n'
    '  ctx.font=SML; ctx.fillStyle=DIM; ctx.fillText("HULL",L,y);\n'
    '  ctx.font=SML; ctx.fillStyle=hpPct<0.25?"#ff4444":WHT;\n'
    '  ctx.fillText(ship.hp+" / "+SHIP_MAX_HP,L+68,y); y+=4;\n'
    '  hbar(L,y,PW-28,7,hpPct,\n'
    '    hpPct>0.5?"#22bb55":hpPct>0.25?"#aa6600":"#880000",\n'
    '    hpPct>0.5?"#44ff88":hpPct>0.25?"#ffcc00":"#ff2222"); y+=16;\n'
    '  const fuelPct=ship.fuel/FUEL_CAPACITY;\n'
    '  const segW=Math.floor((PW-28)/10)-2, filledSegs=Math.ceil(fuelPct*10);\n'
    '  ctx.font=SML; ctx.fillStyle=DIM; ctx.fillText("FUEL",L,y);\n'
    '  ctx.font=SML; ctx.fillStyle=fuelPct<0.25?ORANGE:WHT;\n'
    '  ctx.fillText(ship.fuel.toFixed(1)+" gal",L+68,y); y+=4;\n'
    '  for(let i=0;i<10;i++){\n'
    '    const lit=i<filledSegs;\n'
    '    ctx.fillStyle=!lit?"#0d1520":fuelPct>0.5?"#3db87a":fuelPct>0.25?"#e6c040":\n'
    '      (fuelPct<0.1&&Math.floor(Date.now()/300)%2===0)?"#ff2222":ORANGE;\n'
    '    ctx.fillRect(L+i*(segW+2),y,segW,10);\n'
    '    ctx.strokeStyle="#4FC3C318"; ctx.lineWidth=0.5;\n'
    '    ctx.strokeRect(L+i*(segW+2),y,segW,10);\n'
    '  }\n'
    '  y+=16;\n'
   f'  if(ship.fuel<=0){{ctx.font=SML;ctx.fillStyle="#ff4444";ctx.fillText("{CROSS} FUEL EMPTY",L,y);y+=LINE;}}\n'
   f'  else if(fuelPct<0.2&&Math.floor(Date.now()/500)%2===0){{ctx.font=SML;ctx.fillStyle=ORANGE;ctx.fillText("{WARN} LOW FUEL",L,y);y+=LINE;}}\n'
    '\n'
    '  // Hull death overlay\n'
    '  if(ship.hp<=0){\n'
    '    if(!ship.destroyed){ship.destroyed=true;ship.destroyedAt=Date.now();\n'
    '      for(let i=0;i<60;i++){const ang=Math.random()*Math.PI*2,spd=1+Math.random()*5;\n'
    '        particles.push({x:canvas.width/2,y:canvas.height/2,vx:Math.cos(ang)*spd,vy:Math.sin(ang)*spd,\n'
    '          life:80+Math.random()*60,maxLife:140,\n'
    '          color:["#ff4444","#ff8800","#ffcc00","#ffffff"][Math.floor(Math.random()*4)],size:2+Math.random()*4});}}\n'
    '    const elapsed=Date.now()-(ship.destroyedAt||Date.now()),remaining=Math.ceil((4000-elapsed)/1000);\n'
    '    ctx.fillStyle="#000000bb";ctx.fillRect(0,0,canvas.width,canvas.height);\n'
    '    ctx.textAlign="center";\n'
   f'    ctx.font="bold 32px Courier New";ctx.fillStyle="#ff2222";ctx.fillText("{CROSS}  SHIP DESTROYED",canvas.width/2,canvas.height/2-30);\n'
    '    ctx.font="20px Courier New";ctx.fillStyle="#ff8800";\n'
    '    ctx.fillText("RESPAWNING IN "+Math.max(0,remaining)+"...",canvas.width/2,canvas.height/2+14);\n'
    '    ctx.textAlign="left";\n'
    '    if(elapsed>=4000){\n'
    '      if(ship.ore>0||ship.mineral>0||ship.armalcolite>0){\n'
    '        worldPods.push({pid:"wreck_"+Date.now(),type:"_wreck",\n'
    '          worldX:ship.worldX+(Math.random()-0.5)*40,worldY:ship.worldY+(Math.random()-0.5)*40,\n'
    '          angle:Math.random()*Math.PI*2,\n'
    '          cargo:{ore:ship.ore,mineral:ship.mineral,armalcolite:ship.armalcolite},label:"WRECK"});}\n'
    '      ship.ore=0;ship.mineral=0;ship.armalcolite=0;\n'
    '      ship.hp=SHIP_MAX_HP;ship.worldX=(Math.random()-0.5)*300;ship.worldY=(Math.random()-0.5)*300;\n'
    '      ship.vx=0;ship.vy=0;ship.destroyed=false;saveGame();\n'
   f'      showToast("RESPAWNED {SEP} cargo lost. Find your wreck.","#f97316");\n'
    '    }\n'
    '    return;\n'
    '  }\n'
    '\n'
    '  // CARGO\n'
    '  sBar(y,"CARGO","#f59e0b"); y+=LINE+2;\n'
    '  const cUsed=cargoUsed(),cMax=ship.shipType.cargoLimit||CARGO_LIMIT;\n'
    '  const cPct=Math.min(cUsed/cMax,1),cFull=cUsed>=cMax;\n'
    '  hbar(L,y,PW-60,6,cPct,\n'
    '    cPct<0.7?"#4FC3C3":cPct<0.95?ORANGE:"#ff2222",\n'
    '    cPct<0.7?"#22aacc":cPct<0.95?"#ffaa44":"#ff6666");\n'
    '  ctx.font=SML; ctx.fillStyle=cFull?"#ef4444":WHT;\n'
    '  ctx.fillText(cUsed+" / "+cMax+(cFull?"  FULL":""),L+(PW-54),y+6); y+=14;\n'
   f'  if(ship.ore>0){{ctx.font="bold 14px monospace";ctx.fillStyle="#FFD700";ctx.fillText("{DIAM}",L+4,y);ctx.font=MED;ctx.fillStyle="#FFD700";ctx.fillText(ship.ore+"  NEBULITE",L+18,y);y+=LINE;}}\n'
   f'  if(ship.mineral>0){{ctx.font="bold 14px monospace";ctx.fillStyle="#a78bfa";ctx.fillText("{LOZZ}",L+4,y);ctx.font=MED;ctx.fillStyle="#c4b5fd";ctx.fillText(ship.mineral+"  MINERAL",L+18,y);y+=LINE;}}\n'
   f'  if(ship.armalcolite>0){{ctx.font="bold 14px monospace";ctx.fillStyle="#34d399";ctx.fillText("{OCTO}",L+4,y);ctx.font=MED;ctx.fillStyle="#6ee7b7";ctx.fillText(ship.armalcolite+"  ARMALCOLITE",L+18,y);y+=LINE;}}\n'
    '  if(cUsed===0){ctx.font=SML;ctx.fillStyle=DIM;ctx.fillText("empty hold",L+4,y);y+=LINE;}\n'
    '\n'
    '  // MODULES\n'
    '  if(attachedPods.length){\n'
    '    sBar(y,"MODULES","#38bdf8"); y+=LINE+2;\n'
    '    attachedPods.forEach(p=>{\n'
   f'      ctx.font="bold 13px monospace";ctx.fillStyle=p.color||"#38bdf8";ctx.fillText("{TARG}",L+4,y);\n'
    '      ctx.font=SML;ctx.fillStyle=p.color||"#38bdf8";ctx.fillText(p.label,L+18,y);\n'
    '      if(p.cargoBonus){ctx.fillStyle=DIM;ctx.fillText("+"+p.cargoBonus+" cargo",L+120,y);}\n'
    '      y+=LINE;\n'
    '    });\n'
    '  }\n'
    '\n'
    '  // ACTIONS\n'
    '  sBar(y,"ACTIONS","#64748b"); y+=LINE+2;\n'
    '  const canCraft=ship.armalcolite>0;\n'
    '  ctx.font=SML;\n'
   f'  ctx.fillStyle=canCraft?"#FFD700":DIM; ctx.fillText("[C]",L,y);\n'
   f'  ctx.fillStyle=canCraft?WHT:DIM; ctx.fillText("REFINE  1 ARM {ARR} +"+FUEL_PER_CRAFT.toFixed(1)+" FUEL",L+26,y); y+=LINE;\n'
    '  ctx.fillStyle=mineTarget?TEAL:DIM; ctx.fillText("[E]",L,y);\n'
    '  ctx.fillStyle=mineTarget?WHT:DIM;\n'
    '  ctx.fillText("MINE"+(mineTarget?"  "+Math.round(mineDist)+"px":""),L+26,y); y+=LINE;\n'
    '\n'
    '  // NETWORK\n'
    '  if(typeof multiMode!=="undefined"&&multiMode){\n'
    '    sBar(y,"NETWORK","#38bdf8"); y+=LINE+2;\n'
    '    ctx.font=SML; ctx.fillStyle="#38bdf8";\n'
   f'    ctx.fillText("{SQUA}  "+(Object.keys(remotePlayers).length+1)+" pilots online",L,y); y+=LINE;\n'
    '  }\n'
    '\n'
    '  // Mini compass\n'
    '  const cx2=10+PW-36,cy2=58,r=22;\n'
    '  ctx.strokeStyle="#1a2a3a"; ctx.lineWidth=1;\n'
    '  ctx.beginPath(); ctx.arc(cx2,cy2,r,0,Math.PI*2); ctx.stroke();\n'
    '  const dirIdx=DIRS.indexOf(ship.dir);\n'
    '  if(dirIdx>=0){\n'
    '    const a=DIR_ANGLES_DEG[dirIdx]*(Math.PI/180);\n'
    '    ctx.strokeStyle=TEAL; ctx.lineWidth=2;\n'
    '    ctx.beginPath(); ctx.moveTo(cx2,cy2);\n'
    '    ctx.lineTo(cx2+Math.cos(a)*(r-4),cy2+Math.sin(a)*(r-4)); ctx.stroke();\n'
    '    ctx.fillStyle=TEAL;\n'
    '    ctx.beginPath(); ctx.arc(cx2+Math.cos(a)*(r-4),cy2+Math.sin(a)*(r-4),3,0,Math.PI*2); ctx.fill();\n'
    '  }\n'
    '  ctx.fillStyle="#1a2a3a88"; ctx.beginPath(); ctx.arc(cx2,cy2,3,0,Math.PI*2); ctx.fill();\n'
    '\n'
    '  // Map zone flash\n'
    '  if(bgFlash&&bgFlash.timer>0){\n'
    '    const alpha=Math.min(1,bgFlash.timer/30);\n'
    '    ctx.globalAlpha=alpha; ctx.fillStyle=TEAL;\n'
    '    ctx.font="18px Courier New"; ctx.textAlign="center";\n'
    '    ctx.fillText("MAP: "+bgFlash.name.replace("_"," ").toUpperCase(),canvas.width/2,canvas.height-30);\n'
    '    ctx.textAlign="left"; ctx.globalAlpha=1; bgFlash.timer--;\n'
    '  }\n'
    '}'
)

d, ok = rsub(r'function drawHUD\(speed\) \{.*?\n\}', NEW_HUD, d)
fixes.append(('OK' if ok else 'FAIL') + ' drawHUD redesigned')

with open('driftbound_flight_test.html', 'wb') as f:
    f.write(d.encode('utf-8'))

for v in fixes:
    print(('  OK  ' if v.startswith('OK') else '  FAIL ') + v[2:].strip())
